# Generated by Django 4.1.13 on 2026-03-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_propertyindexpage_propertypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypage',
            name='beam',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Beam in meters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='cruising_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cruising speed in knots', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='draft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Draft in meters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='hull',
            field=models.CharField(blank=True, help_text='Hull material (e.g. Steel)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='refit_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Refit Year'),
        ),
        migrations.AddField(
            model_name='propertypage',
            name='sold_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypage',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Build year', null=True, verbose_name='Build Year'),
        ),
    ]
