# Generated by Django 4.1.13 on 2026-03-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_propertypage_beam_propertypage_cruising_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypage',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
    ]
